# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binlist <- function(filename, vname, bins) {
    .Call('rrshdf4_binlist', PACKAGE = 'rrshdf4', filename, vname, bins)
}

#' Vdata names and field names in HDF4. 
#' 
#' Retrieve vdata names and their field names from HDF4. 
#' @param file name of HDF4 file containing Vdata
#' @return Named list, each element with the field names of the named Vdata. 
#' @export
#' @examples
#' \dontrun{
#' f <- "A2014202.L3b_DAY_PIC.main"
#' if (!file.exists(f)) {
#'   srcf <- sprintf("http://oceandata.sci.gsfc.nasa.gov/cgi/getfile/%s.bz2", f)
#'   download.file(srcf, sprintf("%s.bz2", f), mode = "wb")
#'   system(sprintf("bunzip2 %s.bz2", f))
#' } 
#'   vdatainfo(f)
#' 
#' 
#' }
vdatainfo <- function(file) {
    .Call('rrshdf4_vdatainfo', PACKAGE = 'rrshdf4', file)
}

